// Word categories in Spanish for EL FEKA game
export const CATEGORIES = {
  futbol: {
  name: "FÚTBOL",
  emoji: "⚽",
  words: [
    "Messi",
    "Cristiano Ronaldo",
    "Mbappé",
    "Haaland",
    "Neymar",
    "Vinícius",
    "Modrić",
    "Iniesta",
    "Xavi",
    "Maradona",
    "Pelé",
    "Zidane",
    "Guardiola",
    "Ancelotti",
    "Mourinho",
    "Klopp",
    "Scaloni",
    "Luis Enrique",
    "Simeone",
    "Bielsa",
    "Real Madrid",
    "Barcelona",
    "Manchester City",
    "Liverpool",
    "Bayern Múnich",
    "PSG",
    "Juventus",
    "Inter",
    "Milan",
    "Atlético de Madrid",
    "Selección Alemania",
    "Selección Brasil",
    "Selección España",
    "Champions League",
    "Mundial",
    "Penalti",
    "Gol",
    "Portero",
    "Defensa",
    "Centrocampista",
    "Delantero",
    "Árbitro",
    "Offside",
    "Tarjeta roja",
    "Tarjeta amarilla",
    "Estadio",
    "Afición",
    "Clásico",
    "Derbi",
    "Táctica"
  ]
},
  deportes: {
  name: "DEPORTES Y JUEGOS",
  emoji: "🏅",
  words: [
    "Fútbol",
    "Baloncesto",
    "Béisbol",
    "Tenis",
    "Hockey",
    "Golf",
    "Natación",
    "Atletismo",
    "Voleibol",
    "Bádminton",
    "Bolos",
    "Rugby",
    "Skate",
    "Surf",
    "Lacrosse",
    "Kárate",
    "Gimnasia",
    "Tiro con arco",
    "Polo",
    "Esgrima",
    "Equitación",
    "Triatlón",
    "Jabalina",
    "Críquet",
    "Ajedrez",
    "Damas",
    "Póker",
    "Dominó",
    "Dardos",
    "Ping pong",
    "Ciclismo",
    "Lucha libre",
    "Boxeo",
    "Judo",
    "Taekwondo",
    "Patinaje sobre hielo",
    "Esquí",
    "Snowboard",
    "Patines",
    "Softball",
    "Billar",
    "Videojuegos",
    "Parchís"
  ]
},
  tecnologia: {
    name: "TECNOLOGÍA",
    emoji: "📱",
    words: [
      "iPhone",
      "PlayStation",
      "Inteligencia Artificial",
      "Wifi",
      "Robot",
      "Laptop",
      "Drone",
      "Bitcoin",
      "TikTok",
      "Instagram",
      "Spotify",
      "YouTube",
      "Tesla",
      "Alexa",
      "ChatGPT",
    ],
  },
  musica: {
    name: "MÚSICA",
    emoji: "🎵",
    words: [
      "Reparto",
      "Reggaetón",
      "Salsa",
      "Rock",
      "Hip Hop",
      "Bachata",
      "Cumbia",
      "Merengue",
      "Pop",
      "Trap",
      "R&B",
      "Electrónica",
      "Balada",
      "Corrido",
      "Mariachi",
      "Jazz",
    ],
  },
comida: {
  name: "COMIDA",
  emoji: "🍕",
  words: [
    "Pizza",
    "Manzana",
    "Pan",
    "Pastel",
    "Helado",
    "Plátano",
    "Sándwich",
    "Leche",
    "Galleta",
    "Queso",
    "Espagueti",
    "Hamburguesa",
    "Palomitas",
    "Ensalada",
    "Taco",
    "Yogur",
    "Cereal",
    "Pollo",
    "Croissant",
    "Sushi",
    "Guacamole",
    "Berenjena",
    "Aguacate",
    "Dona",
    "Waffle",
    "Pasta",
    "Sopa",
    "Brócoli",
    "Bistec",
    "Salmón",
    "Atún",
    "Maíz",
    "Frijoles",
    "Arroz",
    "Papa",
    "Tomate",
    "Lechuga",
    "Cebolla",
    "Tocino"
  ]
},
peliculas: {
  name: "CINE & SERIES",
  emoji: "🎬",
  words: [
    "Frozen",
    "Toy Story",
    "Spider-Man",
    "Minions",
    "Batman",
    "Vampiros en La Habana",
    "Moana",
    "Shrek",
    "Harry Potter",
    "Star Wars",
    "Parque Jurásico",
    "Buscando a Nemo",
    "Pantera Negra",
    "Aladdín",
    "El Rey León",
    "E.T.",
    "Cenicienta",
    "Encanto",
    "Origen",
    "Casablanca",
    "El Padrino",
    "Parásitos",
    "Interestelar",
    "La lista de Schindler",
    "Tiburón",
    "Titanic",
    "La La Land",
    "Avatar",
    "Vengadores",
    "Iron Man",
    "Thor",
    "Capitán América",
    "Crepúsculo",
    "Matrix",
    "El Resplandor",
    "Psicosis",
    "Forrest Gump",
    "Tras la Huella",
    "Gladiador",
    "Madagascar",
    "Friends",
    "Los Simpson"
  ]
},
lugares: {
  name: "LUGARES",
  emoji: "📍",
  words: [
    "Escuela",
    "Parque",
    "Playa",
    "Casa",
    "Zoológico",
    "Granja",
    "Patio de juegos",
    "Centro comercial",
    "Hospital",
    "Biblioteca",
    "Ayuntamiento",
    "Estadio",
    "Aeropuerto",
    "Teatro",
    "Acuario",
    "Museo",
    "Restaurante",
    "Castillo",
    "Montaña",
    "Puente",
    "Pirámides",
    "Torre Eiffel",
    "Gran Muralla",
    "Taj Mahal",
    "Coliseo",
    "Machu Picchu",
    "Stonehenge",
    "Ópera de Sídney",
    "Estatua de la Libertad",
    "Monte Everest",
    "Iglesia",
    "Mezquita",
    "Templo",
    "Sinagoga",
    "Mercado",
    "Oficina",
    "Gimnasio",
    "Bar",
    "Cafetería",
    "Panadería",
    "Carnicería",
    "Floristería",
    "Librería",
    "Farmacia",
    "Banco",
    "Oficina de correos",
    "Puerto",
    "Estación de tren",
    "Plaza"
  ]
},
profesiones: {
  name: "PROFESIONES",
  emoji: "💼",
  words: [
    "Maestro",
    "Doctor",
    "Chef",
    "Granjero",
    "Enfermero",
    "Bombero",
    "Policía",
    "Cantante",
    "Atleta",
    "Piloto",
    "Bibliotecario",
    "Ingeniero",
    "Abogado",
    "Bailarín",
    "Mecánico",
    "Científico",
    "Actor",
    "Escritor",
    "Soldado",
    "Panadero",
    "Arqueólogo",
    "Astrónomo",
    "Matemático",
    "Diseñador de moda",
    "Diplomático",
    "Geólogo",
    "Biólogo",
    "Escultor",
    "Político",
    "Arquitecto",
    "Contable",
    "Banquero",
    "Carpintero",
    "Electricista",
    "Fontanero",
    "Dentista",
    "Veterinario",
    "Terapeuta",
    "Entrenador",
    "Árbitro",
    "Juez",
    "Alcalde",
    "Gerente",
    "Secretario",
    "Recepcionista",
    "Conserje",
    "Periodista",
    "Fotógrafo",
    "Programador"
  ]
},
  fiestas: {
    name: "FIESTAS",
    emoji: "🎉",
    words: [
      "Cumpleaños",
      "Boda",
      "Halloween",
      "Navidad",
      "Año Nuevo",
      "Quinceañera",
      "Bautizo",
      "Graduación",
      "Baby Shower",
      "Carnaval",
      "San Valentín",
      "Día de Muertos",
      "Pool Party",
      "Despedida",
      "Fin de Año",
    ],
  },
  ciencia: {
    name: "CIENCIA",
    emoji: "🔬",
    words: [
      "Átomo",
      "Vacuna",
      "Gravedad",
      "NASA",
      "Microscopio",
      "ADN",
      "Laboratorio",
      "Experimento",
      "Planeta",
      "Eclipse",
      "Química",
      "Física",
      "Biología",
      "Telescopio",
      "Fósil",
    ],
  },
nerds: {
  name: "NERD",
  emoji: "🤓",
  words: [
    "Paradoja",
    "Metafísica",
    "Epistemología",
    "Anacronismo",
    "Hipérbole",
    "Paradigma",
    "Espectro",
    "Cryptografía",
    "Algoritmo",
    "Singularidad",
    "Cuántico",
    "Neurona",
    "Sinapsis",
    "Ambivalente",
    "Dissonancia",
    "Hermenéutica",
    "Simetría",
    "Isótopo",
    "Invariante",
    "Anómalo",
    "Complejidad",
    "Holograma",
    "Multiverso",
    "Iteración",
    "Recursivo",
    "Determinismo",
    "Estocástico",
    "Ecléctico",
    "Idiosincrasia",
    "Conjetura",
    "Postulado",
    "Entrelazamiento",
    "Polimorfismo",
    "Abstracción",
    "Metadato",
    "Escepticismo",
    "Catarsis",
    "Eureka",
    "Némesis",
    "Utopía"
  ]
},
  objetos: {
  name: "OBJETOS Y COSAS",
  emoji: "📦",
  words: [
    "Pelota",
    "Silla",
    "Libro",
    "Teléfono",
    "Cama",
    "Mesa",
    "Zapatos",
    "Sombrero",
    "Bolígrafo",
    "Reloj",
    "Mochila",
    "Cámara",
    "Guitarra",
    "Bicicleta",
    "Paraguas",
    "Espejo",
    "Radio",
    "Manta",
    "Maleta",
    "Microondas",
    "Telescopio",
    "Máquina de escribir",
    "Microscopio",
    "Proyector",
    "Brújula",
    "Termómetro",
    "Acordeón",
    "Saxofón",
    "Máquina de coser",
    "Dron",
    "Lámpara",
    "Cuadro",
    "Cortina",
    "Almohada",
    "Alfombra",
    "Sofá",
    "Sillón",
    "Escritorio",
    "Armario",
    "Puerta",
    "Ventana",
    "Llave",
    "Candado",
    "Cadena",
    "Cuerda",
    "Escalera",
    "Martillo",
    "Serrucho",
    "Llave inglesa",
    "Escoba"
  ]
},
  vehiculos: {
  name: "VEHÍCULOS Y TRANSPORTE",
  emoji: "🚗",
  words: [
    "Coche",
    "Autobús",
    "Bici",
    "Barco",
    "Camión",
    "Tren",
    "Avión",
    "Taxi",
    "Furgoneta",
    "Patineta",
    "Helicóptero",
    "Motocicleta",
    "Velero",
    "Tractor",
    "Submarino",
    "Jeep",
    "Limusina",
    "Globo aerostático",
    "Monopatín",
    "Cohete",
    "Góndola",
    "Aerodeslizador",
    "Teleférico",
    "Moto de nieve",
    "Canoa",
    "Kayak",
    "Yate",
    "Crucero",
    "Barco de carga",
    "Avión de carga",
    "Caza",
    "Dirigible",
    "Carro",
    "Carreta",
    "Triciclo",
    "Moto de agua",
    "Lancha rápida",
    "Remolcador",
    "Ferry",
    "Tranvía",
    "Metro",
    "Scooter eléctrico"
  ]
},
  glitch: {
  name: "GLITCH EN LA MATRIX",
  emoji: "🌀",
  words: [
    "Dejà vu",
    "Simulación",
    "Bug",
    "Lag",
    "NPC",
    "Pantalla azul",
    "Reinicio",
    "Error 404",
    "Parpadeo",
    "Bucle",
    "Pixelado",
    "Desfase",
    "Pantalla negra",
    "Sobrecarga",
    "Desincronizado",
    "Desfase horario",
    "Latencia",
    "Descompilado",
    "Reescritura",
    "Parche",
    "Hackeo",
    "Pantallazo",
    "Frame perdido",
    "Desfase de audio",
    "Flashazo",
    "Corrupción de datos",
    "Rebobinar",
    "Frame congelado",
    "Pantalla partida",
    "Interferencia",
    "Ruido blanco",
    "Distorsión",
    "Anomalía",
    "Eco",
    "Desdoblamiento",
    "Error crítico",
    "Autosave",
    "Backup",
    "Desinstalar"
  ]
},
  cuba: {
    name: "CUBA",
    emoji: "🇨🇺",
    words: [
      "Asere",
      "Yuma",
      "Fula",
      "Guagua",
      "Paladar",
      "Jama",
      "Pasmao'",
      "Socio",
      "Pinchar",
      "Temba",
      "Jinetero",
      "Mango",
      "Papaya",
      "Guajiro",
      "Pinga",
      "Hueso",
      "Bisne",
      "Candela",
      "Ecobio",
      "Monina",
      "Batear",
      "Fiana",
      "Tonga",
      "Pipo",
      "Pura",
    ],
  },
  mixto: {
    name: "MIXTO",
    emoji: "🎲",
    words: [], // Will be filled dynamically
  },
} as const;

export type CategoryKey = keyof typeof CATEGORIES;

export function getRandomWord(category: CategoryKey): {
  word: string;
  category: string;
} {
  if (category === "mixto") {
    const allCategories = Object.keys(CATEGORIES).filter(
      (k) => k !== "mixto"
    ) as CategoryKey[];
    const randomCategory =
      allCategories[Math.floor(Math.random() * allCategories.length)];
    const words = CATEGORIES[randomCategory].words;
    return {
      word: words[Math.floor(Math.random() * words.length)],
      category: CATEGORIES[randomCategory].name,
    };
  }

  const words = CATEGORIES[category].words;
  return {
    word: words[Math.floor(Math.random() * words.length)],
    category: CATEGORIES[category].name,
  };
}

export function selectImpostor(playerCount: number): number {
  return Math.floor(Math.random() * playerCount);
}

export function selectImpostors(playerCount: number, count: number): number[] {
  const indices: number[] = [];
  while (indices.length < count) {
    const rand = Math.floor(Math.random() * playerCount);
    if (!indices.includes(rand)) {
      indices.push(rand);
    }
  }
  return indices;
}
